##  -*-  coding: utf-8; mode: ruby -*-  ##
##  vi: set ft=ruby

Vagrant.configure("2") do |config|
  config.vm.box = "takahiro-itou/ubuntu-jammy64-docker"

  config.vm.provider "virtualbox" do |v|
    v.name   = "vagrant-ubuntu-docker"
    v.memory = "3072"
    v.gui    = false
  end

  config.vm.network(:forwarded_port, guest: 22, host: 11222, id: "ssh")
  config.vm.network("private_network", ip: "192.168.33.12")
  config.vm.synced_folder(".", "/vagrant", disabled: true)
end

load  File.expand_path('common/CommonCustomize.rb')

$disk_image_file = './disk/ubuntu-docker-sdc.vdi'
load  File.expand_path('common/AttachNewhdd.rb')

# Provisioning(s)
load  File.expand_path('common/UploadFiles.rb')
load  File.expand_path('common/SetupUbuntu.rb')
load  File.expand_path('common/RamDisk.rb')
load  File.expand_path('common/SetupUsers.rb')

Vagrant.configure("2") do |config|
  config.vm.provision("docker", type: "shell",
                      path: "provision/docker.sh",
                      privileged: true)
end
