##  -*-  coding: utf-8; mode: ruby -*-  ##
##  vi: set ft=ruby


##########################################################################
##
##    Load Modules
##

load  File.expand_path('common/CommonCustomize.rb')
load  File.expand_path('common/AttachSCSIHdd.rb')

load  File.expand_path('common/UploadFiles.rb')
load  File.expand_path('common/SetupUbuntu.rb')
load  File.expand_path('common/RamDisk.rb')
load  File.expand_path('common/SetupUsers.rb')


##########################################################################
##
##    Configuration
##

Vagrant.configure("2") do |config|
  config.vm.box = "takahiro-itou/ubuntu-jammy64-docker"

  config.vm.provider "virtualbox" do |v|
    v.name   = "vagrant-ubuntu-docker"
    v.memory = "24576"

    v.customize [
      "modifyvm",               :id,
      "--mouse",                "usbtablet",
      "--graphicscontroller",   "vmsvga",
    ]

    v.gui    = false
  end

  config.vm.network(:forwarded_port, guest: 22, host: 11222, id: "ssh")
  config.vm.network("private_network", ip: "192.168.33.12")
  config.vm.synced_folder(".", "/vagrant", disabled: true)

  # For Blog (bundle exec jekyll serve)
  config.vm.network(:forwarded_port, guest: 4000, host: 4012)
end


##########################################################################
##
##    Customize Virtual Machine
##

# Common Customize.

Vagrant.configure("2") do |config|
  customize_config(config)

  config.vm.provider "virtualbox" do |v|
    customize_vm_provider(v)
  end
end

# Attach Disk.

disk_image_file = File.expand_path('./disk/ubuntu-docker-sdc.vdi')

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    attach_scsi_hdd(v, disk_image_file)
  end
  provision_newhdd_scsi(config.vm)
  config_detach_trigger(config)
end

# Provisioning(s)

Vagrant.configure("2") do |config|
  provision_upload_files(config.vm)
end

Vagrant.configure("2") do |config|
  provision_setup_ubuntu(config.vm)
end

Vagrant.configure("2") do |config|
  provision_ram_disk(config.vm)
end

Vagrant.configure("2") do |config|
  provision_setup_users(config.vm)
end

Vagrant.configure("2") do |config|
  config.vm.provision("docker", type: "shell",
                      path: "provision/docker.sh",
                      privileged: true)
end
